apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myflask-test-storage-class
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-standard
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-myflask-test
spec:
  storageClassName: myflask-test-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32M