apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-kustomize-app
spec:
  template:
    spec:
      containers:
        - name: flask-kustomize-container
          env:
            - name: DEPLOYED_CITY
              value: $(DEPLOYED_CITY)
            - name: ENVIRONMENT
              value: $(ENVIRONMENT)